# Walmart Sales Forecast

## 1. Exploração inicial dos dados

Este notebook tem como objetivo realizar a primeira inspeção do conjunto de dados de vendas do Walmart, verificando sua estrutura, variáveis, tipos de dados, valores ausentes e estatísticas descritivas.

### Importação das bibliotecas

In [14]:
import pandas as pd

### Carregamento dos dados

In [15]:
df = pd.read_csv(r"C:\Users\vinic\Desktop\Python\walmart-sales-forecast\data\raw\train.csv")

### Inspeção inicial

In [16]:
df.head(5)

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [17]:
df.shape

(421570, 5)

In [18]:
df.columns.tolist()

['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday']

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  str
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 13.3 MB

### Estatísticas descritivas

In [20]:
df.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

### Qualidade dos dados

In [21]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.nunique()

Store               45
Dept                81
Date               143
Weekly_Sales    359464
IsHoliday            2
dtype: int64

### Tratamento da variável de data

In [25]:
df["Date"] = pd.to_datetime(df["Date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[us]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), datetime64[us](1), float64(1), int64(2)
memory usage: 13.3 MB

In [26]:
data_inicial = df["Date"].min()
data_final = df["Date"].max()

print("Data inicial:", data_inicial)
print("Data final:", data_final)

Data inicial: 2010-02-05 00:00:00
Data final: 2012-10-26 00:00:00

In [28]:
df["Store"].nunique()
df["Store"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [29]:
df["Store"].value_counts()

Store
13    10474
10    10315
4     10272
1     10244
2     10238
24    10228
27    10225
34    10224
20    10214
6     10211
32    10202
19    10148
31    10142
28    10113
41    10088
11    10062
23    10050
14    10040
40    10017
15     9901
8      9895
39     9878
17     9864
18     9859
26     9854
25     9804
7      9762
12     9705
22     9688
45     9637
21     9582
35     9528
29     9455
16     9443
3      9036
5      8999
9      8867
38     7362
37     7206
44     7169
30     7156
42     6953
43     6751
33     6487
36     6222
Name: count, dtype: int64