# Walmart Sales Forecast

## 1. Exploração inicial dos dados

Este notebook tem como objetivo realizar a primeira inspeção do conjunto de dados de vendas do Walmart, verificando sua estrutura, variáveis, tipos de dados, valores ausentes e estatísticas descritivas.

### Importação das bibliotecas

In [32]:
import pandas as pd

### Carregamento dos dados

In [33]:
df = pd.read_csv(r"C:\Users\vinic\Desktop\Python\walmart-sales-forecast\data\raw\train.csv")

### Inspeção inicial

In [34]:
df.head(5)

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [35]:
df.shape

(421570, 5)

In [36]:
df.columns.tolist()

['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday']

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  str
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 13.3 MB

### Estatísticas descritivas

In [38]:
df.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

### Qualidade dos dados

In [39]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)