# Walmart Sales Forecast
# .\.venv\Scripts\Activate.ps1
## 1. Exploração inicial dos dados

Este notebook tem como objetivo realizar a primeira inspeção do conjunto de dados de vendas do Walmart, verificando sua estrutura, variáveis, tipos de dados, valores ausentes e estatísticas descritivas.

### Importação das bibliotecas

In [24]:
import pandas as pd

### Carregamento dos dados

In [25]:
df = pd.read_csv(r"C:\Users\vinic\Desktop\Python\walmart-sales-forecast\data\raw\train.csv")

### Inspeção inicial

In [26]:
df.head(5)

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [27]:
df.shape

(421570, 5)

In [28]:
df.columns.tolist()

['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday']

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  str
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 13.3 MB

### Estatísticas descritivas

In [30]:
df.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

### Qualidade dos dados

In [31]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.nunique()

Store               45
Dept                81
Date               143
Weekly_Sales    359464
IsHoliday            2
dtype: int64

### Tratamento da variável de data

In [56]:
df["Date"] = pd.to_datetime(df["Date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[us]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
 5   Year          421570 non-null  int32
 6   Month         421570 non-null  int32
dtypes: bool(1), datetime64[us](1), float64(1), int32(2), int64(2)
memory usage: 16.5 MB

### Tratamento da variável de data

In [57]:
data_inicial = df["Date"].min()
data_final = df["Date"].max()

### Período dos dados

In [70]:
print("Data inicial:", data_inicial)
print("Data final:", data_final)

Data inicial: 2010-02-05 00:00:00
Data final: 2012-10-26 00:00:00

### Lojas e departamentos

In [71]:
df["Store"].nunique()

45

In [72]:
df["Store"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [73]:
df["Store"].value_counts()

Store
13    10474
10    10315
4     10272
1     10244
2     10238
24    10228
27    10225
34    10224
20    10214
6     10211
32    10202
19    10148
31    10142
28    10113
41    10088
11    10062
23    10050
14    10040
40    10017
15     9901
8      9895
39     9878
17     9864
18     9859
26     9854
25     9804
7      9762
12     9705
22     9688
45     9637
21     9582
35     9528
29     9455
16     9443
3      9036
5      8999
9      8867
38     7362
37     7206
44     7169
30     7156
42     6953
43     6751
33     6487
36     6222
Name: count, dtype: int64

### Distribuição de semanas de feriado

In [74]:
df["IsHoliday"].value_counts(normalize=True)

IsHoliday
False    0.929642
True     0.070358
Name: proportion, dtype: float64

### Vendas por loja

In [75]:
vendas_por_loja = df.groupby("Store")["Weekly_Sales"].sum()

vendas_por_loja.sort_values(ascending=False).head()

Store
20    3.013978e+08
4     2.995440e+08
14    2.889999e+08
13    2.865177e+08
2     2.753824e+08
Name: Weekly_Sales, dtype: float64

### Comparação entre feriados e semanas normais

In [76]:
df.groupby("IsHoliday")["Weekly_Sales"].mean()

IsHoliday
False    15901.445069
True     17035.823187
Name: Weekly_Sales, dtype: float64

In [77]:
df.groupby("IsHoliday")["Weekly_Sales"].median()

IsHoliday
False    7589.95
True     7947.74
Name: Weekly_Sales, dtype: float64

### Criação de variáveis temporais

In [78]:
df["Year"] = df["Date"].dt.year

In [79]:
df["Month"] = df["Date"].dt.month

In [80]:
df.head()

   Store  Dept       Date  Weekly_Sales  IsHoliday  Year  Month
0      1     1 2010-02-05      24924.50      False  2010      2
1      1     1 2010-02-12      46039.49       True  2010      2
2      1     1 2010-02-19      41595.55      False  2010      2
3      1     1 2010-02-26      19403.54      False  2010      2
4      1     1 2010-03-05      21827.90      False  2010      3


### Análise por ano e mês

In [81]:
df.groupby("Year")["Weekly_Sales"].sum()

Year
2010    2.288886e+09
2011    2.448200e+09
2012    2.000133e+09
Name: Weekly_Sales, dtype: float64

In [82]:
df.groupby("Month")["Weekly_Sales"].mean().sort_values(ascending=False)

Month
12    19355.702141
11    17491.031424
6     16326.137002
8     16062.516933
2     16008.779217
7     15861.419650
5     15776.337202
4     15650.338357
3     15416.657597
10    15243.855576
9     15095.886154
1     14126.075111
Name: Weekly_Sales, dtype: float64